#Ansible is not able to work with "dnf module" outside of installing them.
#Shell has to be used to check if a specific app stream is enabled, and then disable and enable
#the appropriate app streams to get the correct nodejs version for Yarn.
- name: Check if NodeJS 10 module is enabled
  become: yes
  shell: "dnf module list nodejs | grep -q 'nodejs 10 \\[d\\]\\[e\\]' && echo true || echo false"
  register: is_node10_enabled
  ignore_errors: true
  when: 
  - ansible_os_family == "RedHat"
  - ansible_facts['distribution_major_version'] == "8"

- name: Disable NodeJS 10 module
  become: yes
  shell: "dnf module disable nodejs:10 -y"
  ignore_errors: true
  when: 
  - ansible_os_family == "RedHat"
  - ansible_facts['distribution_major_version'] == "8"
  - is_node10_enabled.stdout | bool

- name: Enable NodeJS 20 module
  become: yes
  shell: "dnf module enable nodejs:20 -y"
  ignore_errors: true
  when: 
  - ansible_os_family == "RedHat"
  - ansible_facts['distribution_major_version'] == "8"
  - is_node10_enabled.stdout | bool

- name: Install NodeJS 20 via DNF
  become: yes
  dnf:
    name: "@nodejs:20"
    state: present
  when: 
  - ansible_os_family == "RedHat"
  - ansible_facts['distribution_major_version'] == "8"  

# RHEL9 installs NodeJS 16 by default, higher needed for corepack
- name: Install NodeJS via DNF
  become: yes
  dnf:
    name: "@nodejs:20"
    state: present
  when: 
  - ansible_os_family == "RedHat"
  - ansible_facts['distribution_major_version'] == "9"  
# RHEL Distros do not bundle Corepack with NodeJS as it's Opt-in only
# https://yarnpkg.com/corepack#installation
- name: Install Corepack via NPM
  become: yes
  npm:
    name: corepack
    global: true
  when: 
  - ansible_os_family == "RedHat"



- name: Enable NodeJS Corepack for Yarn
  shell: "corepack enable"